
-- Create projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text not null,
  tags text[] not null default '{}',
  github_url text not null,
  live_url text,
  image_url text,
  case_study jsonb
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;

-- Create policy to allow read access to everyone
create policy "Enable read access for all users"
  on public.projects for select
  using (true);

-- Create policy to allow insert/update/delete for authenticated users only
-- For development/demo purposes, you might want to allow anon inserts temporarily
-- or ensure you are logged in.
create policy "Enable insert for authenticated users only"
  on public.projects for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
  on public.projects for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
  on public.projects for delete
  using (auth.role() = 'authenticated');

-- ============================================
-- Contact Submissions Table
-- ============================================
-- Stores contact form submissions as a backup
-- and for record-keeping purposes

create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  ip_address text,
  is_read boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.contact_submissions enable row level security;

-- Only authenticated users (admin) can read submissions
create policy "Enable read for authenticated users only"
  on public.contact_submissions for select
  using (auth.role() = 'authenticated');

-- Allow anonymous inserts (from the contact form)
create policy "Enable insert for anonymous users"
  on public.contact_submissions for insert
  with check (true);

-- Only authenticated users can update (mark as read)
create policy "Enable update for authenticated users only"
  on public.contact_submissions for update
  using (auth.role() = 'authenticated');

-- Only authenticated users can delete
create policy "Enable delete for authenticated users only"
  on public.contact_submissions for delete
  using (auth.role() = 'authenticated');
