
-- Create projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text not null,
  tags text[] not null default '{}',
  github_url text not null,
  live_url text,
  case_study jsonb
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;

-- Create policy to allow read access to everyone
create policy "Enable read access for all users"
  on public.projects for select
  using (true);

-- Create policy to allow insert/update/delete for authenticated users only
-- For development/demo purposes, you might want to allow anon inserts temporarily
-- or ensure you are logged in.
create policy "Enable insert for authenticated users only"
  on public.projects for insert
  with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
  on public.projects for update
  using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
  on public.projects for delete
  using (auth.role() = 'authenticated');
